version: '3'

services:
  auth-demo:
    container_name: auth-demo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/auth_demo  # Correct database host
      SPRING_DATASOURCE_USERNAME: auth_demo
      SPRING_DATASOURCE_PASSWORD: auth_demo
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: auth_demo
      POSTGRES_USER: auth_demo
      POSTGRES_PASSWORD: auth_demo
