spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_demo  # Change localhost to db
    username: auth_demo
    password: auth_demo
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 8080
