spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/auth_demo  # Change localhost to db
    username: auth_demo
    password: auth_demo
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
